import type { NextPage } from "next";
import Head from "next/head";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { Quotebar } from "~/components/quotebar";
import { Navbar } from "~/components/navbar";
dayjs.extend(relativeTime);

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>Guestbook | joshlim.dev</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main
        className="relative flex min-h-screen flex-row flex-wrap items-center justify-center gap-5 overflow-hidden bg-gradient-to-b from-[#005506] to-[#002d0e]
        p-5 text-white"
      >
        <Navbar currPage="projects" />
        <Quotebar
          quote={
            "Within our collective streams of consciousness, lies the power to shape extraordinary realities. — ChatGPT"
          }
        />
      </main>
    </>
  );
};

export default Projects;
